# Generated by Django 4.2.6 on 2024-01-24 14:54

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[Store.models.validate_image_type]),
        ),
        migrations.DeleteModel(
            name='ColorImage',
        ),
    ]
