# Generated by Django 4.2.6 on 2024-01-24 14:58

import Store.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_userprofile_profile_image_delete_colorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variantimg', models.ImageField(upload_to='', validators=[Store.models.validate_image_type])),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorimages', to='Store.variant')),
            ],
        ),
    ]
