# Generated by Django 4.2.6 on 2024-01-25 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_images',
            name='cover_image',
            field=models.ImageField(upload_to='main_img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
