# Generated by Django 4.2.6 on 2024-02-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_delete_mymodel_alter_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
