# Generated by Django 4.2.6 on 2024-02-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
